name: Run tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.org'

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: make test
